import { Place } from "@/lib/types";

export const mockPlaces: Place[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    name: "Tichuca Rooftop Bar",
    slug: "tichuca-rooftop-bar",
    description: "야경이 좋은 인기 루프탑 바",
    address: "สุขุมวิท 40, Bangkok",
    district: "Sukhumvit",
    category: "루프탑",
    tags: ["야경", "데이트", "BTS근처"],
    latitude: 13.7242,
    longitude: 100.5697,
    google_map_url: "https://maps.google.com/",
    thumbnail: null,
    tips: "해질 무렵 입장 추천",
    is_published: true,
    is_featured: true,
    last_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    name: "Sarnies Bangkok",
    slug: "sarnies-bangkok",
    description: "브런치와 커피가 강한 카페",
    address: "Charoen Krung, Bangkok",
    district: "Bang Rak",
    category: "카페",
    tags: ["감성", "혼자여행", "사진맛집"],
    latitude: 13.7305,
    longitude: 100.5146,
    google_map_url: "https://maps.google.com/",
    thumbnail: null,
    tips: "주말 오전은 대기 많음",
    is_published: true,
    is_featured: false,
    last_verified_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
