import { Place } from "@/lib/types";

const now = new Date().toISOString();

export const mockPlaces: Place[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    name: "Tichuca Rooftop Bar",
    slug: "tichuca-rooftop-bar",
    city: "Bangkok",
    description: "방콕 대표 루프탑 바 / Bangkok rooftop with skyline view",
    address: "T-One Building, Sukhumvit, Bangkok, Thailand",
    district: "Sukhumvit",
    category: "Rooftop",
    tags: ["야경", "데이트", "BTS 근처"],
    latitude: 13.7242,
    longitude: 100.5697,
    google_map_url: "https://maps.google.com/",
    thumbnail: null,
    tips: "저녁 시간 방문 추천",
    is_published: true,
    is_featured: true,
    submission_status: "approved",
    submitted_by: null,
    last_verified_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    name: "Sarnies Bangkok",
    slug: "sarnies-bangkok",
    city: "Bangkok",
    description: "브런치와 커피가 강한 카페 / Brunch-focused cafe",
    address: "Charoen Krung, Bang Rak, Bangkok, Thailand",
    district: "Bang Rak",
    category: "Cafe",
    tags: ["감성", "혼자여행", "사진"],
    latitude: 13.7305,
    longitude: 100.5146,
    google_map_url: "https://maps.google.com/",
    thumbnail: null,
    tips: "주말 오전은 대기 많음",
    is_published: true,
    is_featured: false,
    submission_status: "approved",
    submitted_by: null,
    last_verified_at: now,
    created_at: now,
    updated_at: now,
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    name: "Jodd Fairs Night Market",
    slug: "jodd-fairs-night-market",
    city: "Bangkok",
    description: "스트리트 푸드와 쇼핑 야시장 / Night market for food and shopping",
    address: "Rama IX, Bangkok, Thailand",
    district: "Ratchada",
    category: "Night Market",
    tags: ["로컬", "친구", "새벽영업"],
    latitude: 13.7579,
    longitude: 100.5654,
    google_map_url: "https://maps.google.com/",
    thumbnail: null,
    tips: "오후 7시 이후 방문 추천",
    is_published: true,
    is_featured: false,
    submission_status: "approved",
    submitted_by: null,
    last_verified_at: now,
    created_at: now,
    updated_at: now,
  },
];

